AppLozic/Applozic-Web-Plugin

src/js/app/modules/socket/applozic.socket.js

replaced jquery selectors with vanilla javascript selectors in applozic.sockets.js

Javascript

---

public/plugin/js/app/fullview/applozic.fullview.js

Reverts AppLozic/Applozic-Web-Plugin#168

Revert "GLAD-320"

---

public/plugin/sample/temp/fullviewtest.html

for testing purpose, will revert after testing is done

testing purpose

---

public/plugin/js/app/modules/group/applozic.group.js
public/plugin/js/app/sidebox/applozic.sidebox.js

-> The role indicator in group info is not updating when success response for role change of group member
-> change role of a user from group info tab, then click update. After success response from server comes, the role text is updated to changed role.
->
->

Change role of group member is not working in web plugin

---

public/plugin/js/app/fullview/applozic.fullview.js

forward message was going to same chat
-> forward message should go to intended receiver
-> sent a message to chat. right click on message then click forward. select user to send the message to.
->
->

GLAD-568 Forward message is not working in fullview plugin

---

public/plugin/js/app/modules/socket/applozic.socket.js

-> variable was not initializing
-> initialized the variable then checked on local server
->
->

GLAD-599 Open group subscription bug

---

public/plugin/sample/core.html
public/plugin/sample/fullview.html
public/plugin/sample/sidebox.html

-> Missed these changes in previous pull reuqest.

Update minified file urls in html files [RELEASE 5.4]

---

config/default.json
config/prod.json
config/staging.json
config/test.json
public/plugin/sample/core.html
public/plugin/sample/fullview.html
public/plugin/sample/sidebox.html

<!---
Please fill these details, it will help the reviewers.
- Wrong minified file was generated previously.
- Update previous version file also but since it was getting cached in aws server, we created a new file with version 5.4.1.

Update cdn file url.

---

public/plugin/js/app/fullview/applozic.fullview.js

-> add setting for showing username in open groups
-> tested in localhost
->
->

Glad 605 1

---

config/default.json
config/prod.json
config/staging.json
config/test.json
public/plugin/sample/core.html
public/plugin/sample/fullview.html
public/plugin/sample/sidebox.html
public/plugin/sample/temp/fullviewtest.html
public/plugin/sample/temp/sideboxtest.html

-> Update minified file url for new release.

Update minified file url for new release.

---

public/plugin/js/app/sidebox/applozic.sidebox.js

->When sidebox panel is hidden and new message notification comes, then by clicking on notification opens tab but it is not scrolled to latest message.
->
->
->

Glad 654 When notification clicked, it should go to most recent message

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/sidebox/applozic.sidebox.js

-> Add alert message for special characters and disable user creation by default in search
-> Tested in localhost
->
->

Glad-521-1 Add alert for special characters and disable user creation by default in search plugin

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/modules/api/applozic.api.js
public/plugin/js/app/sidebox/applozic.sidebox.js

-> Add setting for adding contact list from user's friend list. Maintain contact list on client side for different processes.
-> Created a contact list group for user from sideboxtest.html file and then added members in group programmatically when sending or receiving messages.
->
->

Glad 658 2 Add setting for populating contacts from user's friend list

---

public/plugin/js/app/modules/api/applozic.api.js

GLAD-696 Add authorization header for file upload to Google server	

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/sidebox/applozic.sidebox.js

GLAD-696 Add authorization header for file upload to Google server

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/sidebox/applozic.sidebox.js

-> Add header in api call to redirected url.
->
->
->

GLAD-696-1 Add authorization header for file upload to Google server

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/sidebox/applozic.sidebox.js

-> Added setting in fullview for passing in appOptions to populate contacts from friend list
->
->
->

Glad 658 Add setting for populating contacts from user's friend list	

---

public/plugin/sample/temp/fullviewtest.html
public/plugin/sample/temp/sideboxtest.html

This reverts commit 43019dd3aaaec8d740f9bcedd9aaa23957365c80.
->
->
->
->

reverting changes for test

---

public/plugin/sample/core.html
public/plugin/sample/fullview.html
public/plugin/sample/sidebox.html

Glad 696 1

---

config/default.json
config/prod.json
config/staging.json
config/test.json
public/plugin/sample/core.html
public/plugin/sample/fullview.html
public/plugin/sample/sidebox.html

Applozic dev

---

public/plugin/js/app/sidebox/applozic.sidebox.js

-> Add setting for showing username in open group in sidebox web plugin
->
->
->

GLAD-605 Add setting for showing username in open group in sidebox web plugin

---

public/plugin/js/app/sidebox/applozic.sidebox.js

-> Message is not getting sync web plugin multiple device.
->
->
->

Gald 610 Message is not getting sync web plugin multiple device

---

public/plugin/js/app/fullview/applozic.fullview.js

-> Chat-launcher-icon is showing double the value of unread messages. Added fix for this.
-> Tested in local by adding <span class="chat-launcher-icon"></span> in fullview.html file.
->
->

GLAD-721 Unread count on chat-launcher-icon is getting doubled in fullview plugin

---

public/plugin/css/app/fullview/applozic.fullview.css
public/plugin/css/app/fullview/applozic.plugin.css
public/plugin/css/app/sidebox/applozic.sidebox.css

-> Change pointer on contact image in group info.
->
->
->

GLAD-601 left pointing arrow pointer change into hyperlink pointer

---

public/plugin/js/app/sidebox/applozic.sidebox.js

-> Old messages were not coming in sidebox. Please see https://applozic.atlassian.net/browse/GLAD-750.
->
->
->

GLAD-750 All conversation list is not getting uploaded for web plugin

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/sidebox/applozic.sidebox.js

-> Escape html characters escaping when rendering message.
->
->
->

Glad-789 Use html character escaping

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/sidebox/applozic.sidebox.js

GLAD-789 Use html character escaping in web plugin

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/sidebox/applozic.sidebox.js

-> Html was not escaping characters when rendering.
->
->
->

GLAD-789 Use html character escaping in web plugin and server script code

---

public/plugin/js/app/sidebox/applozic.sidebox.js

GLAD-787 Unread count on chat launcher not updating

---

public/plugin/js/app/sidebox/applozic.sidebox.js

GLAD-787 Unread count issue on chat launcher

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/sidebox/applozic.sidebox.js

Add check for network online/offline when reconnecting socket

---

public/plugin/css/app/fullview/applozic.fullview.css
public/plugin/sample/fullview.html
public/plugin/sample/temp/fullviewtest.html

-> Changed .fade css selector to .mck-fade in fullview.
->
->
->

css changes

---

config/default.json
config/prod.json
config/staging.json
config/test.json
public/plugin/sample/core.html
public/plugin/sample/fullview.html
public/plugin/sample/sidebox.html

-> Updated chat.min.js file name.
->
->
->

Release-5.7

---

public/plugin/js/app/sidebox/applozic.sidebox.js

-> Messages are not rendering on loading tab first time
->
->
->

Glad-878 Messages are not rendering on loading tab first time

---

config/default.json
config/prod.json
config/staging.json
config/test.json
public/plugin/sample/core.html
public/plugin/sample/fullview.html
public/plugin/sample/sidebox.html

update applozic.chat-5.8.min.js file
->
->
->
->

GLAD-878 Update applozic.chat-5.8.min.js

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/modules/socket/applozic.socket.js

->  Encryption for websocket in fullview
-> Sending and receive a message in fullview
->
->

FW-274 Encryption for websocket in fullview

---

public/plugin/js/app/modules/api/applozic.api.js
public/plugin/sample/core.html
public/plugin/sample/temp/coretest.html

-> update app version code to 111
-> login to sidebox and full view, send message and see chat history.
->
->

FW-274 update app version code to 111

---

public/plugin/js/app/applozic.common.js
public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/modules/message/applozic.message.js
public/plugin/js/app/sidebox/applozic.sidebox.js

GLAD-929  Move message related functions to applozic.common.js

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/modules/message/applozic.message.js
public/plugin/js/app/sidebox/applozic.sidebox.js

Reverts AppLozic/Applozic-Web-Plugin#338

Revert "GLAD-929  Move message related functions to applozic.common.js"

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/modules/socket/applozic.socket.js

-> Disable socket level encryption if application encryption is disabled.
->
->
->

Ignore websocket encryption of application encryption is disabled

---

.gitignore
public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/modules/socket/applozic.socket.js

-> Merge changes for websocket encryption which are done in the master branch
->
->
->

Merge changes for websocket encryption

---

public/plugin/sample/fullview.html
public/plugin/sample/sidebox.html
public/plugin/sample/temp/fullviewtest.html
public/plugin/sample/temp/sideboxtest.html

Used local minified file for test

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/modules/socket/applozic.socket.js

-> Revert heartbeat changes as memory issue wasn't fixed with this change.
->
->
->

Revert heartbeat

---

config/default.json
config/prod.json
config/staging.json
config/test.json
public/plugin/sample/core.html
public/plugin/sample/fullview.html
public/plugin/sample/sidebox.html
public/plugin/sample/temp/fullviewtest.html
public/plugin/sample/temp/sideboxtest.html

Change minified file version.

---

public/plugin/js/app/fullview/applozic.fullview.js
public/plugin/js/app/sidebox/applozic.sidebox.js

-->Avoid creating extra bot users for Applozic Application 
-> ![image](https://user-images.githubusercontent.com/21999182/81537976-ab2fdf80-938b-11ea-8050-611e70e5b90a.png)
->
->

Glad 1128 , Avoid creating extra bot users for Applozic Application

---

public/plugin/js/app/applozic.common.js

- Remove special characters if any from the decrypted data.
- By checking location sharing is working or not.
- Location sharing was not working because of special characters.

Remove special characters if any from the decrypted data.

---

public/plugin/js/app/fullview/applozic.fullview.js

- Add a new socket connect logic in full view.
- By connecting socket in full view.

Add new socket connect logic in fullview.
